# Generated by Django 4.1 on 2022-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="server_group",
        ),
        migrations.AddField(
            model_name="server",
            name="server_groups",
            field=models.ManyToManyField(
                to="hub.servergroup", verbose_name="Server Groups"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_document",
            field=models.JSONField(
                default=dict,
                help_text="A JSON object containing a policy describing permissions for Users, Groups, Servers and Server Groups",
                null=True,
                verbose_name="Policy Document",
            ),
        ),
    ]
