# Generated by Django 4.1 on 2022-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name_plural": "Policies"},
        ),
        migrations.AlterModelOptions(
            name="servergroup",
            options={"verbose_name_plural": "Server Groups"},
        ),
        migrations.AlterField(
            model_name="server",
            name="fqdn",
            field=models.CharField(max_length=1004, unique=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="ipv4_address",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
