# Generated by Django 4.1.2 on 2022-10-31 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Rule ID's sourced by this Policy.",
                to="hub.rule",
                verbose_name="Rules",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="servergroups",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Server Group ID's whose members are targetted by this Policy.",
                to="hub.servergroup",
                verbose_name="Target Server Groups",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="servers",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Server ID's that are targetted by this Policy.",
                to="hub.server",
                verbose_name="Target Servers",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="source_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Group ID's whose members are permitted as sources by this Rule.",
                to="auth.group",
                verbose_name="Source Groups",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="source_servergroups",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Server Group ID's whose members are permitted as sources by this Rule.",
                to="hub.servergroup",
                verbose_name="Source Server Groups",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="source_servers",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Server ID's that are permitted as sources by this Rule.",
                to="hub.server",
                verbose_name="Source Servers",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="source_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of User ID's that are permitted as sources by this Rule.",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Source Users",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="server_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of Server Gropup ID's in which this Server is a member.",
                to="hub.servergroup",
                verbose_name="Server Groups",
            ),
        ),
    ]
