# Generated by Django 4.1 on 2022-09-18 00:22

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_server_connected"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_mode", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hub Configuration",
            },
        ),
        migrations.AlterField(
            model_name="server",
            name="connected",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="server",
            name="fqdn",
            field=models.CharField(
                max_length=255, unique=True, validators=[hub.models.EvonFQDNValidator]
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="ipv4_address",
            field=models.GenericIPAddressField(
                protocol="IPv4", validators=[hub.models.EvonIPV4Validator]
            ),
        ),
    ]
