# Generated by Django 4.1 on 2022-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_alter_policy_options_alter_servergroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="uuid",
            field=models.CharField(default="", max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
