# Generated by Django 4.1 on 2022-09-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_config_alter_server_connected_alter_server_fqdn_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="config",
            options={"verbose_name": "Config", "verbose_name_plural": "Config"},
        ),
        migrations.AddField(
            model_name="server",
            name="last_connected",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="discovery_mode",
            field=models.BooleanField(
                default=True,
                help_text="Disable to prevent any new Servers from joining your overlay network",
            ),
        ),
    ]
