# Generated by Django 4.1 on 2022-09-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_alter_server_server_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="server_groups",
            field=models.ManyToManyField(
                blank=True, to="hub.servergroup", verbose_name="Server Groups"
            ),
        ),
    ]
