# Generated by Django 4.1 on 2022-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_server_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="fqdn",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
