# Generated by Django 4.1.2 on 2022-11-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_alter_config_ec2_iam_role_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="ec2_iam_role_status",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Health status of your EC2 IAM Role. Must be True (green) in order for this Evon Hub to function correctly. If False (red), please SSH to this EC2 instance and run command 'evon --iam-validate'.",
                verbose_name="EC2 IAM Role Status",
            ),
        ),
    ]
