# Generated by Django 4.1 on 2022-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_alter_rule_destination_ports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(help_text="eg. 'Allow web access'", max_length=200),
        ),
    ]
