# Generated by Django 4.1 on 2022-10-18 13:01

import django.core.validators
from django.db import migrations, models
import hub.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_alter_rule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="uuid_blacklist",
            field=models.TextField(
                default="",
                help_text="Define a comma separated list of Server UUID's that will be disallowed from connecting. Note that any currenty connected Server with a UUID specified here will be forcibly disconnected and deleted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="fqdn",
            field=models.CharField(
                editable=False,
                help_text="This value is set on line 2 of /etc/openvpn/evon.uuid on your connected server, with '.o82ml.dev.evon.link' appended. An index number may be auto added to the first name-part for uniqueness to prevent duplicate FQDN's. To change this value, edit /etc/openvpn/evon.uuid and restart OpenVPN on your endpoint server.",
                max_length=255,
                unique=True,
                validators=[hub.models.EvonFQDNValidator],
                verbose_name="FQDN",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="ipv4_address",
            field=models.GenericIPAddressField(
                editable=False,
                help_text="This value is auto-assigned and is static for the UUID used by this Server.",
                protocol="IPv4",
                validators=[hub.models.EvonIPV4Validator],
                verbose_name="IPv4 Address",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="uuid",
            field=models.CharField(
                editable=False,
                help_text="This value is set on line 1 of /etc/openvpn/evon.uuid on your connected server.",
                max_length=36,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex=re.compile(
                            "^[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}$"
                        )
                    )
                ],
                verbose_name="UUID",
            ),
        ),
    ]
