# Generated by Django 4.1.13 on 2024-01-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_alter_rule_destination_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="passkey",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
