# Generated by Django 4.1 on 2022-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0005_alter_server_fqdn_alter_server_ipv4_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="last_connected",
        ),
        migrations.AddField(
            model_name="server",
            name="disconnected_since",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Disconnected Since"
            ),
        ),
    ]
