# Generated by Django 4.1 on 2022-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0005_config_uuid_blacklist_alter_server_fqdn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="uuid_blacklist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Define a comma separated list of Server UUID's that will be disallowed from connecting. Note that any currenty connected Server with a UUID specified here will be forcibly disconnected and deleted.",
                null=True,
            ),
        ),
    ]
