# Generated by Django 4.1 on 2022-10-04 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hub", "0005_alter_servergroup_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bootstrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bootstrap",
                "verbose_name_plural": "Bootstrap",
            },
        ),
        migrations.CreateModel(
            name="OVPNClientConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenVPN Client",
                "verbose_name_plural": "OpenVPN Client",
            },
        ),
        migrations.RemoveField(
            model_name="policy",
            name="policy_document",
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination_protocol",
                    models.CharField(
                        choices=[("I", "ICMP"), ("T", "TCP"), ("U", "UDP")],
                        max_length=1,
                    ),
                ),
                ("destination_port_from", models.IntegerField(blank=True, null=True)),
                ("destination_port_to", models.IntegerField(blank=True, null=True)),
                (
                    "source_groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="Source Groups"
                    ),
                ),
                (
                    "source_servergroups",
                    models.ManyToManyField(
                        blank=True,
                        to="hub.servergroup",
                        verbose_name="Source Server Groups",
                    ),
                ),
                (
                    "source_servers",
                    models.ManyToManyField(
                        blank=True, to="hub.server", verbose_name="Source Servers"
                    ),
                ),
                (
                    "source_users",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Source Users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rules",
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="rules",
            field=models.ManyToManyField(
                blank=True, to="hub.rule", verbose_name="Rules"
            ),
        ),
    ]
