# Generated by Django 4.1 on 2022-10-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_bootstrap_ovpnclientconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
