# Generated by Django 4.1.2 on 2022-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_alter_config_uuid_blacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="uuid_whitelist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Define a comma separated list of future Server UUID's that will allowed to connect even if discovery mode is disabled.Currently connected servers do not need to be added here as the Hub will always permit existing Server UUID's to connect.",
                null=True,
            ),
        ),
    ]
