# Generated by Django 4.1.2 on 2022-10-26 00:37

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_config_uuid_whitelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="fqdn",
            field=models.CharField(
                editable=False,
                help_text="This value is set on line 2 of /etc/openvpn/evon.uuid on your connected server.An index number may be automatically appended if needed for uniqueness to prevent duplicate FQDN's. To change this value, edit /etc/openvpn/evon.uuid and restart OpenVPN on your endpoint server.",
                max_length=255,
                unique=True,
                validators=[hub.models.EvonFQDNValidator],
                verbose_name="FQDN",
            ),
        ),
    ]
