# Generated by Django 4.1 on 2022-10-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_policy_servers_policy_serversgroups_rule_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="destination_port_from",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="destination_port_to",
        ),
        migrations.AddField(
            model_name="rule",
            name="destination_ports",
            field=models.CharField(
                blank=True,
                help_text="Comma separated port numbers and dashed ranges, eg: 80,443,7000-8000",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="servers",
            field=models.ManyToManyField(
                blank=True, to="hub.server", verbose_name="Target Servers"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="serversgroups",
            field=models.ManyToManyField(
                blank=True, to="hub.servergroup", verbose_name="Target Server Groups"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="destination_protocol",
            field=models.CharField(
                choices=[
                    ("T", "TCP"),
                    ("U", "UDP"),
                    ("I", "ICMP"),
                    ("A", "Any Protocol"),
                ],
                max_length=1,
            ),
        ),
    ]
