# Generated by Django 4.1 on 2022-10-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0009_remove_rule_destination_port_from_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="policy",
            old_name="serversgroups",
            new_name="servergroups",
        ),
    ]
