# Generated by Django 4.1 on 2022-10-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_rename_serversgroups_policy_servergroups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="destination_protocol",
            field=models.CharField(
                choices=[
                    ("TCP", "TCP"),
                    ("UDP", "UDP"),
                    ("ICMP", "ICMP"),
                    ("ALL", "Any Protocol"),
                ],
                max_length=4,
            ),
        ),
    ]
